import type { Metadata } from "next";
import Providers from "./providers";
import { AdminContainer } from "@/shared/admin-container/ui/AdminContainer";
import { AdminNavbar } from "@/widgets/admin-navbar/ui/AdminNavbar";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning
        className={`antialiased`}
      >
        <Providers>
          <div className="flex gap-3 min-h-screen p-2 bg-blue-100">
            <div className="bg-blue-300 rounded-lg fixed w-10/12 w top-2 right-7 h-10"></div>
            <div className="bg-blue-300 w-[300px] rounded-lg">
              <p className="text-3xl font-bold p-5">Dashboard</p>

              <AdminNavbar />
            </div>
            <AdminContainer>
              {children}
            </AdminContainer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
