import type { Metadata } from "next";
import Providers from "./providers";
import { AdminContainer } from "@/shared/admin-container/ui/AdminContainer";
import { AdminNavbar } from "@/widgets/admin-navbar/ui/AdminNavbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        <Providers>
          {/* Фон */}
          <div
            className="flex gap-3 min-h-screen p-2 relative bg-cover bg-center"
            style={{ backgroundImage: "url('https://img.freepik.com/free-vector/paper-style-smooth-background_23-2148983694.jpg?semt=ais_hybrid&w=740&q=80')" }}
          >
            {/* Верхняя полоска — стекло */}
            <div className="fixed top-2 right-0 w-10/12 h-10 rounded-lg z-20
              bg-white/20 backdrop-blur-md border border-white/30 shadow-sm"
            />

            {/* Сайдбар — стекло */}
            <div className="w-[300px] shrink-0 rounded-lg z-10
              bg-white/25 backdrop-blur-md border border-white/40 shadow-lg"
            >
              <p className="text-3xl font-bold p-5 text-gray-700 drop-shadow-sm">
                Dashboard
              </p>
              <AdminNavbar />
            </div>

            {/* Контент — стекло */}
            <AdminContainer>
              {children}
            </AdminContainer>
          </div>
        </Providers>
      </body>
    </html>
  );
}